name: Publish fennel to npm

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-dependencies-${{ env.cache-name }}-${{ hashFiles('bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-dependencies-${{ env.cache-name }}-
            ${{ runner.os }}-dependencies-
            ${{ runner.os }}-

      - name: Set tag name
        id: get_tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Check if tag is in main branch
        id: check_main_branch
        run: |
          if git merge-base --is-ancestor ${{ env.TAG_NAME }} main; then
            echo "IS_MAIN_BRANCH=true" >> $GITHUB_ENV
          else
            echo "IS_MAIN_BRANCH=false" >> $GITHUB_ENV
          fi

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Update/Install dependencies
        run: bun update

      - name: Test
        run: bun test

      - name: Update npm
        run: npm install -g npm

      - name: Publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          workspace: fennel
          tag: ${{ env.IS_MAIN_BRANCH == 'true' && 'latest' || 'beta' }}


